# Template: Common Go Project - Release (GHCR)
#
# Complete release workflow for Go projects to GitHub Container Registry
# Includes: Docker build/push and Helm chart packaging
#
# Usage:
#   1. Copy this file to your project's .github/workflows/release.yml
#   2. Update image and chart configurations
#   3. Ensure GITHUB_TOKEN has packages:write permission

name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read
  packages: write
  id-token: write
  attestations: write

jobs:
  docker-build:
    name: Build and Push Docker Images
    uses: mandacode-lab/workflows/.github/workflows/docker-build.yml@main
    with:
      images: |
        [
          {"name": "myapp", "dockerfile": "Dockerfile"}
        ]
      registry: ghcr.io
      repository: ${{ github.repository }}
      tag: ${{ github.ref_name }}
      tag-prefix: "v"
      platforms: "linux/amd64"
      enable-provenance: true
      enable-sbom: true
    secrets:
      registry-username: ${{ github.actor }}
      registry-password: ${{ secrets.GITHUB_TOKEN }}

  helm-package:
    name: Package and Push Helm Charts
    needs: docker-build
    uses: mandacode-lab/workflows/.github/workflows/helm-package.yml@main
    with:
      charts: |
        [
          {"dir": "charts/myapp"}
        ]
      registry: ghcr.io
      repository: ${{ github.repository }}
      helm-version: "v4.0.4"
      enable-provenance: true
      skip-existing: true
    secrets:
      registry-username: ${{ github.actor }}
      registry-password: ${{ secrets.GITHUB_TOKEN }}
