# Template: Common Go Project - Pull Request
#
# Complete PR validation workflow for Go projects with Docker and Helm
# Includes: Go CI, Docker testing, and Helm chart testing
#
# Usage:
#   1. Copy this file to your project's .github/workflows/pr.yml
#   2. Update configurations below to match your project structure
#   3. Remove docker-test or helm-test sections if not needed

name: Pull Request

on:
  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: read
  pull-requests: read
  security-events: write

jobs:
  go-ci:
    name: Go CI
    uses: mandacode-lab/workflows/.github/workflows/go-ci.yml@main
    with:
      go-version: "1.23"
      enable-coverage: true
      coverage-threshold: 80
      enable-security-scan: true

  docker-test:
    name: Docker Test
    needs: go-ci
    uses: mandacode-lab/workflows/.github/workflows/docker-test.yml@main
    with:
      images: |
        [
          {"dockerfile": "Dockerfile"}
        ]
      enable-hadolint: true
      enable-trivy: true
      trivy-severity: "HIGH,CRITICAL"

  helm-test:
    name: Helm Test
    uses: mandacode-lab/workflows/.github/workflows/helm-test.yml@main
    with:
      charts: |
        [
          {"dir": "charts/myapp"}
        ]
      helm-version: "v4.0.4"
      kubernetes-version: "v1.31.0"
      enable-kubeconform: true
      enable-install-test: true
