# Template: Common Go Project - Release (AWS ECR)
#
# Complete release workflow for Go projects to AWS ECR
# Includes: Docker build/push to ECR and Helm chart packaging to ECR
#
# Usage:
#   1. Copy this file to your project's .github/workflows/release.yml
#   2. Configure AWS OIDC or add AWS credentials as secrets
#   3. Update AWS region and repository configurations
#   4. Update image and chart configurations

name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read
  id-token: write

jobs:
  docker-build-ecr:
    name: Build and Push Docker Images to ECR
    uses: mandacode-lab/workflows/.github/workflows/docker-build-ecr.yml@main
    with:
      images: |
        [
          {"name": "myapp", "dockerfile": "Dockerfile"}
        ]
      aws-region: ap-northeast-2
      ecr-repository-prefix: mycompany
      tag: ${{ github.ref_name }}
      tag-prefix: "v"
      platforms: "linux/amd64"
      create-repository: true
    secrets:
      # Option 1: OIDC (Recommended)
      aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}

      # Option 2: Access Keys (comment out if using OIDC)
      # aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      # aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  helm-package-ecr:
    name: Package and Push Helm Charts to ECR
    needs: docker-build-ecr
    uses: mandacode-lab/workflows/.github/workflows/helm-package-ecr.yml@main
    with:
      charts: |
        [
          {"dir": "charts/myapp"}
        ]
      aws-region: ap-northeast-2
      ecr-repository-prefix: helm
      helm-version: "v4.0.4"
      skip-existing: true
      create-repository: true
    secrets:
      # Option 1: OIDC (Recommended)
      aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}

      # Option 2: Access Keys (comment out if using OIDC)
      # aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      # aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
