# Template: Migration Image - Release (AWS ECR)
#
# Release workflow for migration Docker images to AWS ECR
# Triggered by migration-specific tags
#
# Usage:
#   1. Copy this file to your project's .github/workflows/migration-release.yml
#   2. Configure AWS OIDC or add AWS credentials as secrets
#   3. Update AWS region and repository configurations
#   4. Update dockerfile location
#   5. Create releases with tags like: migration-v1.0.0

name: Migration Image Release

on:
  push:
    tags:
      - 'migration-v*'

permissions:
  contents: read
  id-token: write

jobs:
  docker-build-ecr:
    name: Build and Push Migration Image to ECR
    uses: mandacode-lab/workflows/.github/workflows/docker-build-ecr.yml@main
    with:
      images: |
        [
          {"name": "migration", "dockerfile": "docker/migration/Dockerfile", "context": "."}
        ]
      aws-region: ap-northeast-2
      ecr-repository-prefix: mycompany
      tag: ${{ github.ref_name }}
      tag-prefix: "migration-v"
      platforms: "linux/amd64"
      create-repository: true
    secrets:
      # Option 1: OIDC (Recommended)
      aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}

      # Option 2: Access Keys (comment out if using OIDC)
      # aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      # aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
