# Template: Migration Image - Release (GHCR)
#
# Release workflow for migration Docker images to GitHub Container Registry
# Triggered by migration-specific tags
#
# Usage:
#   1. Copy this file to your project's .github/workflows/migration-release.yml
#   2. Update the dockerfile location
#   3. Create releases with tags like: migration-v1.0.0

name: Migration Image Release

on:
  push:
    tags:
      - 'migration-v*'

permissions:
  contents: read
  packages: write
  id-token: write
  attestations: write

jobs:
  docker-build:
    name: Build and Push Migration Image
    uses: mandacode-lab/workflows/.github/workflows/docker-build.yml@main
    with:
      images: |
        [
          {"name": "migration", "dockerfile": "docker/migration/Dockerfile", "context": "."}
        ]
      registry: ghcr.io
      repository: ${{ github.repository }}
      tag: ${{ github.ref_name }}
      tag-prefix: "migration-v"
      platforms: "linux/amd64"
      enable-provenance: true
      enable-sbom: true
    secrets:
      registry-username: ${{ github.actor }}
      registry-password: ${{ secrets.GITHUB_TOKEN }}
