# Template: Migration Image - Pull Request
#
# PR validation workflow for migration Docker images
# Only runs when migration-related files change
#
# Usage:
#   1. Copy this file to your project's .github/workflows/migration-pr.yml
#   2. Update the paths filter to match your migration directory structure
#   3. Update the dockerfile path to match your migration Dockerfile location

name: Migration Image PR

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'migrations/**'
      - 'docker/migration/**'
      - 'db/migrations/**'
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read
  security-events: write

jobs:
  docker-test:
    name: Test Migration Docker Image
    # Only run if migration files changed or manually triggered
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request
    uses: mandacode-lab/workflows/.github/workflows/docker-test.yml@main
    with:
      images: |
        [
          {"dockerfile": "docker/migration/Dockerfile", "context": "."}
        ]
      enable-hadolint: true
      enable-trivy: true
      trivy-severity: "HIGH,CRITICAL"
